name: Rails CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: fmug_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.0'
        bundler-cache: true

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - uses: actions/cache@v3
      name: Cache node modules
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install libpq-dev
        bundle install
        yarn install --frozen-lockfile

    - name: Setup and run tests
      env:
        RAILS_ENV: test
        POSTGRES_HOST: localhost
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: fmug_test
        COVERAGE: true
      run: |
        bundle exec rails db:test:prepare
        PARALLEL_WORKERS=2 bundle exec rspec --format documentation
        bundle exec rubocop
